### PR TITLE
Update SECURITY.md

### PR DESCRIPTION
**Pull request by pmnlla**
The following changes were made in this PR:
- The vulnerability disclosure document SECURITY.MD was updated in order to reflect the current changes to Kyo's build identifiers, in which case the current public beta build is 29 and current devel build is 30.
- The vulnerability disclosure document SECURITY.MD was updated in order to reflect the current changes to Kyo's current features and structure, where a new application, Cosmic, will be entering closed beta soon and is currently in development.

### CODE REVIEW

**Review by rainyskye — APPROVED** [review]
lgtm

**Comment by rainyskye** [comment]
why ur pr note longer then the commit 🤯 

for future reference, all it needs is:
```
changed stuff, fuck it we ball
```

**Comment by pmnlla** [comment]
because it's a shitload of boilerplate text. that's why. but fuck it we ball

**Comment by rainyskye** [comment]
> because it's a shitload of boilerplate text. that's why. 

bad. shut up.

> but fuck it we ball

good 👍

**Comment by pmnlla** [comment]
🫵

**Pull request merged**
